name: Deploy Vite TypeScript Site

on:
  push:
    branches: [ "Ziadui" ] # Triggers whenever you push code to main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env: 
          VITE_API_URL: 'https://straggler-twistable-carwash.ngrok-free.dev'
        run: npm run build # This runs the TypeScript compiler and Vite build

      - name: Upload Production Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # Uploads the compiled folder, not your raw files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
